### ISSUE TITLE
Create table as carbondata table from mysql query does not work

### ISSUE THREAD

**Issue by yangjiajun2014** [openlookeng/hetu-core#16]
### Software Environment:
- OpenLooKeng version (source or binary):
010
- OS platform & distribution (eg., Linux Ubuntu 16.04):

- Java version:
### Describe the current behavior
1.8

### Describe the expected behavior
Create a carbondata table from a mysql query.Does openlookeng support such operation?

### Steps to reproduce the issue
1.Register a mysql data source and a carbondata source to openlookeng
2.Do a query looks like 'create TABLE  carbondata.default.table as select somthing from mysql.schema.table'
3.Run the query with jdbc driver.My test throws such exception:Exception in thread "main" java.sql.SQLException: Query failed (#20200827_065416_00000_vkdav): org.apache.hadoop.io.ByteWritable cannot be cast to org.apache.hadoop.hive.serde2.io.ByteWritable

### Special notes for this issue

**Comment by AbhishekNew** [comment]
@yangjiajun2014 can u take the latest openLooKeng Version and test. 09/30

**Comment by AbhishekNew** [comment]
Handled this Exception against the in PR https://gitee.com/openlookeng/hetu-core/pulls/48

**Comment by AbhishekNew** [comment]
Verified with mysql connector also
