### ISSUE TITLE
hetu-hazelcast  depends com.sun:tools:jar witch removed since JDK9

### ISSUE THREAD

**Issue by ufolr** [openlookeng/hetu-core#18]
### Software Environment:
- OpenLooKeng version (source or binary):
source 
- OS platform & distribution (eg., Linux Ubuntu 16.04):

- Java version:
### Describe the current behavior
I use `mvn clean install -DskipTest` to build hetu-core with JDK 14, and it break by a dependency error:
```
[ERROR] Failed to execute goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile (default) on project hetu-hazelcast: Execution default of goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile failed: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.11 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:14.0.1 at specified path {JAVA_HOME}../lib/tools.jar -> [Help 1]
```

### Describe the expected behavior
Success build the project with JDK 14

### Steps to reproduce the issue
1. git clone https://github.com/openlookeng/hetu-core.git
2. cd hetu-core
3. mvn clean install -DskipTest

### Special notes for this issue

**Comment by jiwenyu0531** [comment]
@ufolr currently openLooKeng only support Java 8 Update 161 or higher.  You can try it. 
and Supporting higer JDK version is in our backlog, currently it is not high priority.

Would you mind to tell me whether you can a strong dependency on the JDK 14? Thanks

**Comment by ufolr** [comment]
This PR is already merged in [OpenLooKeng gitee repo](https://gitee.com/openlookeng/hetu-core/pulls/319). So I'll Close this PR on github.
